import fs from 'node:fs'
import path from 'node:path'
import { config } from 'dotenv'
import {
  GITHUB_SECRET_PREFIX,
  GITHUB_SECRET_KEY_FILES,
  ROOT_DIR,
  GITHUB_DIR,
} from './constants.js'
import { processKeyFiles, type Secret } from './keys.js'
import { createGithubDeployYaml } from './template.js'

export function getEnvFilePath(env: string): string {
  return path.join(ROOT_DIR, `.env.${env}`)
}

export function getSecretsFilePath(env: string): string {
  return path.join(GITHUB_DIR, `.secrets.${env}`)
}

export function discoverEnvironments(): string[] {
  const files = fs.readdirSync(ROOT_DIR)
  return files
    .filter(
      (f) =>
        f.startsWith('.env.') &&
        f !== '.env.example' &&
        f !== '.env.local' &&
        !f.endsWith('.local')
    )
    .map((f) => f.replace('.env.', ''))
    .sort()
}

function filterEnvFileForDeployment(envFilePath: string): string {
  const content = fs.readFileSync(envFilePath, 'utf-8')
  const lines = content.split('\n')
  const filteredLines: string[] = []
  let insideMultilineGithubSecret = false

  for (const line of lines) {
    const trimmed = line.trim()

    // Track multiline values (quoted strings that don't close on same line)
    if (insideMultilineGithubSecret) {
      // Check if this line ends the multiline value
      if (trimmed.endsWith('"') || trimmed.endsWith("'")) {
        insideMultilineGithubSecret = false
      }
      continue
    }

    // Skip GITHUB_SECRET_ lines
    if (trimmed.startsWith(GITHUB_SECRET_PREFIX)) {
      // Check if value starts a multiline (opening quote without closing)
      const eqIdx = trimmed.indexOf('=')
      if (eqIdx !== -1) {
        const value = trimmed.slice(eqIdx + 1)
        if (
          (value.startsWith('"') && !value.endsWith('"')) ||
          (value.startsWith("'") && !value.endsWith("'"))
        ) {
          insideMultilineGithubSecret = true
        }
      }
      continue
    }

    filteredLines.push(line)
  }

  // Trim trailing empty lines but keep content intact
  return filteredLines.join('\n').replace(/\n+$/, '\n')
}

function writeSecrets(secrets: Secret[], filePath: string): void {
  // Ensure directory exists
  const dir = path.dirname(filePath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  // Sort alphabetically
  const sorted = [...secrets].sort((a, b) => a.key.localeCompare(b.key))

  const lines = ['# Code generated by scripts CLI, DO NOT EDIT']
  for (const secret of sorted) {
    lines.push(`${secret.key}="${secret.value}"`)
  }
  lines.push('') // trailing newline

  fs.writeFileSync(filePath, lines.join('\n'))
}

export function buildAndUpdateSecrets(env: string): void {
  const envFilePath = getEnvFilePath(env)

  if (!fs.existsSync(envFilePath)) {
    console.error(`Error: ${envFilePath} not found`)
    process.exit(1)
  }

  console.log(`\nProcessing environment: ${env}`)
  console.log(`Reading: ${envFilePath}`)

  // Parse env file
  const parsed = config({ path: envFilePath })
  if (parsed.error) {
    console.error(`Error parsing ${envFilePath}:`, parsed.error)
    process.exit(1)
  }

  const envVars = parsed.parsed || {}
  const secrets: Secret[] = []

  // Extract GITHUB_SECRET_* vars
  for (const [key, value] of Object.entries(envVars)) {
    if (!key.startsWith(GITHUB_SECRET_PREFIX)) continue
    if (!value) continue

    if (key === GITHUB_SECRET_KEY_FILES) {
      // Process key files
      const keySecrets = processKeyFiles(value)
      secrets.push(...keySecrets)
      continue
    }

    // Strip prefix
    const strippedKey = key.slice(GITHUB_SECRET_PREFIX.length)
    secrets.push({ key: strippedKey, value })
  }

  // Create ENV_B64 - filtered env content (no GITHUB_SECRET_ lines)
  const filteredContent = filterEnvFileForDeployment(envFilePath)
  const envB64 = Buffer.from(filteredContent).toString('base64')
  secrets.push({ key: 'ENV_B64', value: envB64 })

  // Write .github/.secrets.{env}
  const secretsFilePath = getSecretsFilePath(env)
  writeSecrets(secrets, secretsFilePath)
  console.log(`Written: ${secretsFilePath} (${secrets.length} secrets)`)

  // Generate deploy.{env}.yml from template
  createGithubDeployYaml([env])
}
