# https://taskfile.dev

version: "3"

dotenv: [".env"]

includes:
  docker:
    taskfile: .docker/Taskfile.yml
    dir: ./.docker
  scripts:
    taskfile: scripts/Taskfile.yml
    dir: ./scripts
  db:
    taskfile: src/integrations/drizzle/Taskfile.yml
    dir: .
